/*This file was generated by NativeWind. Do not edit!*/
const {
  NativeWindStyleSheet: _NativeWindStyleSheet
} = require("nativewind");
_NativeWindStyleSheet.create({
  styles: {
    "*": {
      "borderTopWidth": 0,
      "borderRightWidth": 0,
      "borderBottomWidth": 0,
      "borderLeftWidth": 0,
      "borderStyle": "solid",
      "borderTopColor": "#e5e7eb",
      "borderRightColor": "#e5e7eb",
      "borderBottomColor": "#e5e7eb",
      "borderLeftColor": "#e5e7eb"
    },
    "": {
      "borderTopWidth": 0,
      "borderRightWidth": 0,
      "borderBottomWidth": 0,
      "borderLeftWidth": 0,
      "borderStyle": "solid",
      "borderTopColor": "#e5e7eb",
      "borderRightColor": "#e5e7eb",
      "borderBottomColor": "#e5e7eb",
      "borderLeftColor": "#e5e7eb"
    },
    "html": {
      "lineHeight": 1.5,
      "fontFamily": "ui-sans-serif"
    },
    ":host": {
      "lineHeight": 1.5,
      "fontFamily": "ui-sans-serif"
    },
    "body": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "hr": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "abbr:where([title])": {
      "textDecorationLine": "underline",
      "textDecorationColor": "black",
      "textDecorationStyle": "dotted"
    },
    "code": {
      "fontFamily": "ui-monospace",
      "fontSize": "1em"
    },
    "kbd": {
      "fontFamily": "ui-monospace",
      "fontSize": "1em"
    },
    "samp": {
      "fontFamily": "ui-monospace",
      "fontSize": "1em"
    },
    "pre": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "small": {
      "fontSize": "80%"
    },
    "sub": {
      "fontSize": "75%",
      "lineHeight": 0,
      "position": "relative"
    },
    "sup": {
      "fontSize": "75%",
      "lineHeight": 0,
      "position": "relative"
    },
    "button": {
      "backgroundColor": "transparent"
    },
    "input": {
      "opacity": 1,
      "color": "#9ca3af"
    },
    "optgroup": {
      "fontFamily": "inherit",
      "fontSize": "100%",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "select": {
      "textTransform": "none"
    },
    "textarea": {
      "opacity": 1,
      "color": "#9ca3af"
    },
    "input:where([type='button'])": {
      "backgroundColor": "transparent"
    },
    "input:where([type='reset'])": {
      "backgroundColor": "transparent"
    },
    "input:where([type='submit'])": {
      "backgroundColor": "transparent"
    },
    ":-moz-ui-invalid": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "black",
      "shadowOpacity": 1
    },
    "blockquote": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "dl": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "dd": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h1": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h2": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h3": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h4": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h5": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h6": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "figure": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "p": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "fieldset": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "legend": {
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "ol": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "ul": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "menu": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "dialog": {
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "img": {
      "maxWidth": "100%"
    },
    "video": {
      "maxWidth": "100%"
    },
    "[hidden]": {
      "display": "none"
    },
    "absolute": {
      "position": "absolute"
    },
    "relative": {
      "position": "relative"
    },
    "flex": {
      "display": "flex"
    },
    "h-[80%]": {
      "height": "80%"
    },
    "h-full": {
      "height": "100%"
    },
    "w-[10%]": {
      "width": "10%"
    },
    "w-[100%]": {
      "width": "100%"
    },
    "w-[20%]": {
      "width": "20%"
    },
    "w-[70%]": {
      "width": "70%"
    },
    "w-[90%]": {
      "width": "90%"
    },
    "w-full": {
      "width": "100%"
    },
    "max-w-[85%]": {
      "maxWidth": "85%"
    },
    "max-w-[90%]": {
      "maxWidth": "90%"
    },
    "max-w-[98%]": {
      "maxWidth": "98%"
    },
    "flex-1": {
      "flexGrow": 1,
      "flexShrink": 1,
      "flexBasis": "0%"
    },
    "flex-row": {
      "flexDirection": "row"
    },
    "items-start": {
      "alignItems": "flex-start"
    },
    "items-center": {
      "alignItems": "center"
    },
    "justify-start": {
      "justifyContent": "flex-start"
    },
    "justify-end": {
      "justifyContent": "flex-end"
    },
    "justify-center": {
      "justifyContent": "center"
    },
    "justify-between": {
      "justifyContent": "space-between"
    },
    "rounded-3xl": {
      "borderTopLeftRadius": "1.5rem",
      "borderTopRightRadius": "1.5rem",
      "borderBottomRightRadius": "1.5rem",
      "borderBottomLeftRadius": "1.5rem"
    },
    "rounded-full": {
      "borderTopLeftRadius": 9999,
      "borderTopRightRadius": 9999,
      "borderBottomRightRadius": 9999,
      "borderBottomLeftRadius": 9999
    },
    "rounded-lg": {
      "borderTopLeftRadius": "0.5rem",
      "borderTopRightRadius": "0.5rem",
      "borderBottomRightRadius": "0.5rem",
      "borderBottomLeftRadius": "0.5rem"
    },
    "bg-black/10": {
      "backgroundColor": "rgba(0, 0, 0, 0.1)"
    },
    "bg-gray-100": {
      "backgroundColor": "rgba(243, 244, 246, 1)"
    },
    "bg-gray-200": {
      "backgroundColor": "rgba(229, 231, 235, 1)"
    },
    "bg-green-700": {
      "backgroundColor": "rgba(21, 128, 61, 1)"
    },
    "bg-green-900": {
      "backgroundColor": "rgba(20, 83, 45, 1)"
    },
    "bg-neutral-100": {
      "backgroundColor": "rgba(245, 245, 245, 1)"
    },
    "bg-white": {
      "backgroundColor": "rgba(255, 255, 255, 1)"
    },
    "text-center": {
      "textAlign": "center"
    },
    "text-2xl": {
      "fontSize": "1.5rem",
    },
    "text-3xl": {
      "fontSize": "1.875rem",
    },
    "text-4xl": {
      "fontSize": "2.25rem",
    },
    "text-base": {
      "fontSize": "1rem",
    },
    "text-sm": {
      "fontSize": "0.875rem",
    },
    "text-xl": {
      "fontSize": "1.25rem",
    },
    "text-xs": {
      "fontSize": "0.75rem",
    },
    "font-bold": {
      "fontWeight": "700"
    },
    "font-extrabold": {
      "fontWeight": "800"
    },
    "font-medium": {
      "fontWeight": "500"
    },
    "font-semibold": {
      "fontWeight": "600"
    },
    "uppercase": {
      "textTransform": "uppercase"
    },
    "capitalize": {
      "textTransform": "capitalize"
    },
    "tracking-wider": {
      "letterSpacing": "0.05em"
    },
    "text-black": {
      "color": "rgba(0, 0, 0, 1)"
    },
    "text-gray-600": {
      "color": "rgba(75, 85, 99, 1)"
    },
    "text-gray-700": {
      "color": "rgba(55, 65, 81, 1)"
    },
    "text-gray-900": {
      "color": "rgba(17, 24, 39, 1)"
    },
    "text-green-800": {
      "color": "rgba(22, 101, 52, 1)"
    },
    "text-green-900": {
      "color": "rgba(20, 83, 45, 1)"
    },
    "text-neutral-300": {
      "color": "rgba(212, 212, 212, 1)"
    },
    "text-neutral-800": {
      "color": "rgba(38, 38, 38, 1)"
    },
    "text-white": {
      "color": "rgba(255, 255, 255, 1)"
    },
    "dark:bg-green-800@0": {
      "backgroundColor": "rgba(22, 101, 52, 1)"
    },
    "dark:bg-green-800@1": {
      "backgroundColor": "rgba(22, 101, 52, 1)"
    },
    "dark:bg-green-800@2": {
      "backgroundColor": "rgba(22, 101, 52, 1)"
    },
    "dark:bg-neutral-400@0": {
      "backgroundColor": "rgba(163, 163, 163, 1)"
    },
    "dark:bg-neutral-400@1": {
      "backgroundColor": "rgba(163, 163, 163, 1)"
    },
    "dark:bg-neutral-400@2": {
      "backgroundColor": "rgba(163, 163, 163, 1)"
    },
    "dark:bg-neutral-900@0": {
      "backgroundColor": "rgba(23, 23, 23, 1)"
    },
    "dark:bg-neutral-900@1": {
      "backgroundColor": "rgba(23, 23, 23, 1)"
    },
    "dark:bg-neutral-900@2": {
      "backgroundColor": "rgba(23, 23, 23, 1)"
    },
    "dark:text-neutral-300@0": {
      "color": "rgba(212, 212, 212, 1)"
    },
    "dark:text-neutral-300@1": {
      "color": "rgba(212, 212, 212, 1)"
    },
    "dark:text-neutral-300@2": {
      "color": "rgba(212, 212, 212, 1)"
    },
    "dark:text-neutral-600@0": {
      "color": "rgba(82, 82, 82, 1)"
    },
    "dark:text-neutral-600@1": {
      "color": "rgba(82, 82, 82, 1)"
    },
    "dark:text-neutral-600@2": {
      "color": "rgba(82, 82, 82, 1)"
    },
    "dark:text-white@0": {
      "color": "rgba(255, 255, 255, 1)"
    },
    "dark:text-white@1": {
      "color": "rgba(255, 255, 255, 1)"
    },
    "dark:text-white@2": {
      "color": "rgba(255, 255, 255, 1)"
    }
  },
  atRules: {
    "dark:bg-green-800": [[["media", "(prefers-color-scheme: dark)"], ["media", "(prefers-color-scheme: dark)"]], [["media", "(prefers-color-scheme: dark)"], ["media", "(prefers-color-scheme: dark)"]], [["media", "(prefers-color-scheme: dark)"], ["media", "(prefers-color-scheme: dark)"]]],
    "dark:bg-neutral-400": [[["media", "(prefers-color-scheme: dark)"], ["media", "(prefers-color-scheme: dark)"]], [["media", "(prefers-color-scheme: dark)"], ["media", "(prefers-color-scheme: dark)"]], [["media", "(prefers-color-scheme: dark)"], ["media", "(prefers-color-scheme: dark)"]]],
    "dark:bg-neutral-900": [[["media", "(prefers-color-scheme: dark)"], ["media", "(prefers-color-scheme: dark)"]], [["media", "(prefers-color-scheme: dark)"], ["media", "(prefers-color-scheme: dark)"]], [["media", "(prefers-color-scheme: dark)"], ["media", "(prefers-color-scheme: dark)"]]],
    "dark:text-neutral-300": [[["media", "(prefers-color-scheme: dark)"], ["media", "(prefers-color-scheme: dark)"]], [["media", "(prefers-color-scheme: dark)"], ["media", "(prefers-color-scheme: dark)"]], [["media", "(prefers-color-scheme: dark)"], ["media", "(prefers-color-scheme: dark)"]]],
    "dark:text-neutral-600": [[["media", "(prefers-color-scheme: dark)"], ["media", "(prefers-color-scheme: dark)"]], [["media", "(prefers-color-scheme: dark)"], ["media", "(prefers-color-scheme: dark)"]], [["media", "(prefers-color-scheme: dark)"], ["media", "(prefers-color-scheme: dark)"]]],
    "dark:text-white": [[["media", "(prefers-color-scheme: dark)"], ["media", "(prefers-color-scheme: dark)"]], [["media", "(prefers-color-scheme: dark)"], ["media", "(prefers-color-scheme: dark)"]], [["media", "(prefers-color-scheme: dark)"], ["media", "(prefers-color-scheme: dark)"]]]
  }
});